
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["forge-std/=lib/forge-std/src/"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
